document.getElementById("generateIntro").addEventListener("click", () => {
    // Get user input
    const name = document.getElementById("name").value.trim();
    const profession = document.getElementById("profession").value.trim();
    const skills = document.getElementById("skills").value.trim();

    // Validate input
    if (name === "" || profession === "" || skills === "") {
        alert(" 🙄Please fill out all fields!😤");
        return;
    }

    // Dynamically update the self-introduction card
    document.getElementById("introName").textContent = `Hello, I'm  ${name}❤️!`;
    document.getElementById("introProfession").textContent = `I am From ${profession}.`;
    let self = document.getElementById("introSkills")

    if(skills == "UI/UX DESIGNER" || skills == "ui/ux designer" || skills=="UI/UX Designer"){
        self.textContent = " As a passionate UI/UX Designer, I craft intuitive and user-friendly designs that resonate with users. I focus on understanding user needs, conducting research, and creating wireframes and prototypes that bridge the gap between creativity and functionality. Proficient in tools like Figma, Sketch, and Adobe XD, I strive to deliver seamless user experiences. My expertise extends to usability testing and iterating designs based on feedback to ensure optimal satisfaction. With an eye for detail and a deep understanding of design principles, I create visually compelling interfaces. I excel in collaborating with cross-functional teams to bring ideas to life. My designs balance aesthetics and functionality to drive user engagement. I'm adept at adapting to emerging trends and technologies in the UI/UX domain. I’m driven by the challenge of solving complex design problems. Let’s build impactful digital experiences together."
    }

    else if (skills == "Graphics Designer" || skills == "graphics designer" || skills=="GRAPHICS DESIGNER"){
        self.textContent = "As a Graphics Designer, I transform concepts into compelling visuals that leave a lasting impression. With a solid command of tools like Adobe Photoshop, Illustrator, and InDesign, I create designs that align with brand identities and marketing goals. My work ranges from logo creation to marketing materials, ensuring visual consistency and impact. I thrive on brainstorming and conceptualizing creative ideas to communicate messages effectively. With a keen eye for color, typography, and layout, I deliver designs that captivate audiences. My collaborative approach ensures client satisfaction and alignment with project objectives. I am proficient in understanding design briefs and translating them into stunning visuals. From digital assets to print designs, I adapt my skills to a variety of mediums. Staying updated with design trends allows me to infuse fresh creativity into my work. I am passionate about making brands stand out through design excellence."
    }
    else if (skills == "Front-End Developer" || skills == "front end developer" || skills=="FRONT END DEVELPER"){
        self.textContent ="As a Front-End Developer, I bring designs to life through clean and efficient code. Specializing in HTML, CSS, and JavaScript, I create responsive and interactive web pages that work seamlessly across devices. My experience with frameworks like React and Vue.js allows me to build dynamic and modern interfaces. I am adept at translating UI/UX designs into pixel-perfect implementations. With a focus on performance and usability, I optimize websites for faster load times and enhanced user experiences. I enjoy collaborating with designers and backend developers to deliver cohesive solutions. Proficient in debugging and browser compatibility, I ensure robust functionality across platforms. My attention to detail helps me craft intuitive navigation and engaging user interactions. Staying updated with front-end technologies and trends is integral to my approach. I’m passionate about creating web applications that are not just functional but also visually captivating."
    }
    else if (skills == "UI Developer" || skills == "ui developer" || skills=="UI DEVELOPER"){
        self.textContent = "As a UI Developer, I specialize in building visually stunning and user-centric interfaces. With expertise in HTML, CSS, JavaScript, and frameworks like Angular or React, I ensure seamless front-end development. My role bridges the gap between design and functionality, translating UI/UX designs into responsive and interactive applications. I am skilled in maintaining code quality, scalability, and adhering to industry standards. My focus is on delivering pixel-perfect designs that enhance user engagement. I collaborate closely with designers and developers to create cohesive and impactful web solutions. Proficient in debugging and performance optimization, I ensure smooth user experiences. My adaptability to new tools and frameworks keeps my skillset current in this fast-evolving field. I am committed to creating applications that combine aesthetics with usability. Let’s innovate and build exceptional digital products together."
    }
    else if (skills == "Software Developer" || skills == "software developer" || skills == "SOFTWARE DEVELOPER"){
        self.textContent = "As a Software Developer, I enjoy creating efficient and scalable software solutions. Proficient in languages like Java, Python, and C++, I bring robust coding expertise to my projects. I thrive in problem-solving, writing clean and maintainable code to meet complex requirements. My experience spans developing desktop, web, and mobile applications tailored to client needs. I am skilled in working with databases, APIs, and integrating third-party services. I follow agile development practices to ensure timely delivery and continuous improvement. Staying updated with the latest technologies helps me bring innovative solutions to the table. I value collaboration and have worked effectively in cross-functional teams. Whether it's debugging, testing, or deploying, I handle challenges with a solution-driven approach. I aim to build software that not only functions well but also creates value for users."
    }

    else if (skills == "Web Developer" || skills == "web developer" || skills == "WEB DEVELOPER"){
        self.textContent = "As a Web Developer, I specialize in building robust and scalable websites tailored to meet client requirements. My skill set includes HTML, CSS, JavaScript, and frameworks like React and Angular. I am adept at both frontend and backend development, ensuring seamless integration and functionality. My experience spans working with databases, optimizing website performance, and enhancing user experiences. I stay updated with emerging web technologies to deliver modern and engaging solutions. With a focus on responsive design, I ensure websites perform well across all devices. I enjoy collaborating with designers and other developers to create cohesive projects. Proficient in debugging and troubleshooting, I solve issues efficiently. My goal is to create websites that are not only visually appealing but also highly functional. I am passionate about turning ideas into digital realities that make an impact."
    }

    else if (skills == "Web Designer" || skills == "web designer" || skills == "WEB DESIGNER"){
        self.textContent = "As a Web Designer, I craft visually appealing and user-friendly websites that align with client goals. My expertise includes wireframing, prototyping, and creating responsive designs that work seamlessly across devices. Proficient in tools like Adobe XD, Figma, and WordPress, I translate ideas into engaging web experiences. My designs focus on aesthetics, usability, and performance to maximize user engagement. I am skilled in HTML and CSS, enabling me to collaborate closely with developers for smooth implementations. Staying updated with web design trends and best practices helps me deliver modern and impactful solutions. My attention to detail ensures pixel-perfect designs that resonate with target audiences. I thrive in brainstorming creative ideas and turning them into functional websites. I prioritize delivering projects on time and exceeding client expectations. Together, let’s create websites that leave a lasting impression."
    }
    else if (skills == "Python Developer" || skills == "python developer" || skills == "PYTHON DEVELOPER"){
        self.textContent = "As a Python Developer, I build efficient and scalable solutions to tackle complex challenges. Proficient in Python frameworks like Django and Flask, I develop dynamic web applications and APIs. My expertise includes data analysis, automation, and scripting to optimize workflows. I am skilled in working with databases like PostgreSQL and MongoDB for robust backend support. With a focus on clean and maintainable code, I ensure high-quality software development. My adaptability allows me to handle diverse projects, from web development to data-driven applications. I enjoy collaborating with teams to deliver tailored solutions that meet business needs. I am constantly learning new libraries and tools to enhance my capabilities. Proficient in debugging and performance optimization, I ensure seamless application functionality. Let’s innovate and build software solutions that make a difference."
    }

    else if (skills == "Java Developer" || skills == "java developer" || skills == "JAVA DEVELOPER"){
        self.textContent = "As a Java Developer, I specialize in building robust and scalable applications using Java and its frameworks like Spring and Hibernate. I excel in creating efficient backend systems and APIs that power modern applications. My skills include working with databases, designing object-oriented solutions, and writing clean, maintainable code. I enjoy solving complex problems and implementing efficient algorithms to optimize performance. I collaborate effectively with cross-functional teams to deliver high-quality software solutions. Proficient in debugging and testing, I ensure application reliability and stability. My expertise extends to deploying and maintaining applications in diverse environments. Staying updated with the latest Java advancements allows me to deliver innovative solutions. I am passionate about creating software that drives business success. Let’s work together to develop applications that make an impact."
    }

    else if (skills == "Full-Stack Developer" || skills == "Full Stack Developer" || skills == "full-stack developer" || skills == "full stack developer"){
        self.textContent = "As a Full-Stack Developer, I bring expertise in both frontend and backend development to create comprehensive web solutions. Proficient in JavaScript, HTML, CSS, and frameworks like React, Angular, Node.js, and Django, I deliver end-to-end development. My experience includes designing and managing databases, building APIs, and ensuring responsive design for all devices. I thrive on problem-solving and writing clean, scalable, and maintainable code. My approach focuses on delivering seamless user experiences and robust backend functionality. I excel in collaborating with teams to transform ideas into functional and appealing digital products. With a commitment to staying updated, I incorporate the latest tools and technologies into my projects. I am skilled in debugging, testing, and optimizing applications for maximum efficiency. Let’s collaborate to build innovative and impactful web applications."
    }

    else if (skills == "MERN Stack Developer" || skills == "mern stack developer" || skills == "MERN STACK DEVELOPER"){
        self.textContent = "As a MERN Stack Developer, I create dynamic and scalable web applications using MongoDB, Express.js, React, and Node.js. I specialize in building responsive user interfaces and powerful backend systems. My expertise includes developing RESTful APIs, managing databases, and ensuring seamless integration between the frontend and backend. I follow agile methodologies to deliver projects efficiently and effectively. Proficient in debugging and performance optimization, I ensure robust and efficient applications. My adaptability allows me to work on diverse projects, from single-page applications to complex web platforms. I stay updated with the latest technologies in the MERN stack to deliver cutting-edge solutions. I excel in collaborating with designers and developers to create cohesive products. My passion lies in developing web applications that are both functional and visually engaging. Let’s bring your ideas to life with the power of MERN."
    }

    else if (skills == "HR Recruiter" || skills == "hr recruiter" || skills == "HR RECRUITER"){
        self.textContent = "As an HR Recruiter, I specialize in identifying, attracting, and hiring top talent to meet organizational needs. My expertise lies in crafting compelling job descriptions, sourcing candidates through various channels, and conducting thorough interviews. I excel in leveraging recruitment tools and platforms to ensure efficient hiring processes. Building strong relationships with candidates and understanding their career goals is my priority. I focus on aligning the right talent with the right roles to foster growth and productivity. My ability to manage multiple openings simultaneously ensures timely delivery of recruitment objectives. I am skilled in screening resumes, coordinating interviews, and negotiating offers. Staying updated with industry trends helps me refine strategies and attract top-performing professionals. I thrive in creating a positive candidate experience while achieving organizational hiring goals. Let’s connect and build a workforce that drives success."
    }

    else if (skills == "HR Executive" || skills == "hr executive" || skills == "HR EXECUTIVE"){
        self.textContent = "As an HR Executive, I manage and enhance the human resources functions to support business objectives. My expertise includes recruitment, onboarding, employee engagement, and performance management. I strive to create a positive workplace culture by addressing employee needs and fostering collaboration. Proficient in HR software and tools, I ensure smooth operations and maintain accurate records. I am skilled in policy implementation, training, and resolving workplace conflicts to maintain harmony. My ability to balance organizational goals with employee satisfaction drives productivity and retention. I excel in strategizing HR practices to align with company growth and compliance standards. Staying updated with labor laws and HR trends ensures my practices are effective and relevant. I enjoy contributing to a thriving workplace by optimizing human capital. Let’s build an organization where employees and businesses grow together."
    }

    else if (skills == "Digital Marketing Analyst" || skills == "digital marketing analyst" || skills == "DIGITAL MARKETING ANALYST"){
        self.textContent = "As a Digital Marketing Analyst, I turn data into actionable insights to drive marketing success. I specialize in analyzing website traffic, campaign performance, and audience behavior to optimize strategies. Proficient in tools like Google Analytics, SEMrush, and Excel, I deliver detailed reports to guide decision-making. My expertise includes tracking KPIs, identifying trends, and suggesting improvements to maximize ROI. I excel in conducting competitor analysis to identify opportunities for growth. By monitoring digital channels, I ensure campaigns are performing at their best. My ability to interpret complex data and communicate insights helps teams make informed decisions. Staying updated with industry trends and analytics tools enhances my analytical approach. I thrive on helping brands improve their digital presence and achieve measurable results. Let’s turn numbers into growth stories together."
    }

    else if (skills == "Digital Marketing Executive" || skills == "digital marketing executive" || skills == "DIGITAL MARKETING EXECUTIVE"){
        self.textContent = "As a Digital Marketing Analyst, I turn data into actionable insights to drive marketing success. I specialize in analyzing website traffic, campaign performance, and audience behavior to optimize strategies. Proficient in tools like Google Analytics, SEMrush, and Excel, I deliver detailed reports to guide decision-making. My expertise includes tracking KPIs, identifying trends, and suggesting improvements to maximize ROI. I excel in conducting competitor analysis to identify opportunities for growth. By monitoring digital channels, I ensure campaigns are performing at their best. My ability to interpret complex data and communicate insights helps teams make informed decisions. Staying updated with industry trends and analytics tools enhances my analytical approach. I thrive on helping brands improve their digital presence and achieve measurable results. Let’s turn numbers into growth stories together."
    }

    else{
        self.textContent="Oop's😱 To write a correct position😤 Like ❤️ (eg: UI/UX Designer, Web Developer) "
    }




    // Show the intro card
    const introCard = document.getElementById("introCard");
    introCard.style.display = "block";
});
